name: chatapp_firebase
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.20
  cloud_firestore: ^3.1.18
  firebase_core: ^1.18.0
  firebase_database: ^9.0.17
  google_sign_in: ^5.3.3
  connectivity_plus: ^2.3.5
  chat_bubbles: ^1.3.0
  emoji_selector: ^0.0.2
  get_storage: ^2.0.3
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_spinkit: ^5.1.0
  image_picker: ^0.8.5+3
  path: ^1.8.1
  path_provider: ^2.0.11
  firebase_storage: ^10.3.2
  flutter_facebook_auth: ^4.4.0+1
  github_sign_in: ^0.0.5-dev.4
  animated_text_kit: ^4.2.2
  animations: ^2.0.3
  page_transition: ^2.0.9

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
   - assets/

  fonts:
    - family: MochiyPopOne
      fonts:
        - asset: assets/MochiyPopOne.ttf
    - family: RobotoMono
      fonts:
        - asset: assets/RobotoMono.ttf
      
